### [1] 전체 기업 비교 현황 조회 (나의 기업 선택 횟수 기준 내림차순)
GET http://localhost:7777/api/resultCompare?sortBy=pickAsMyStartupCount&order=desc


###

### [2] 전체 기업 비교 현황 조회 (비교 기업 선택 횟수 기준 오름차순)
GET http://localhost:7777/api/resultCompare?sortBy=pickAsComparisonCount&order=asc
