### [1] 기업 등록
POST http://localhost:7777/startups
Content-Type: application/json

{
  "companyName": "코드잇",
  "introduce": "온라인 코딩 교육 서비스",
  "category": "에듀테크",
  "totalAmount": 14000000000,
  "salesRevenue": 5000000000,
  "numOfEmployees": 68
}

###
POST http://localhost:7777/startups
Content-Type: application/json

{
  "companyName": "매스프레소",
  "introduce": "AI 교육 플랫폼",
  "category": "에듀테크",
  "totalAmount": 14000000000,
  "salesRevenue": 4200000000,
  "numOfEmployees": 40
}

###
POST http://localhost:7777/startups
Content-Type: application/json

{
  "companyName": "뤼이드",
  "introduce": "실무형 인재 양성",
  "category": "에듀테크",
  "totalAmount": 15000000000,
  "salesRevenue": 4200000000,
  "numOfEmployees": 102
}

###

### [2] 전체 기업 리스트 조회 (투자 총액 포함)
GET http://localhost:7777/startups

###

### [3] 특정 기업 상세 조회
GET http://localhost:7777/startups/1

###

### [4] 기업 삭제
DELETE http://localhost:7777/startups/1

###

### [5] 투자 랭킹 조회
GET http://localhost:7777/startups/rankings
