### 회원가입하기
POST  http://localhost:7777/users/sign-up
Content-Type: application/json

{
    "email": "test@test.com",
    "username": "아무개",
    "password": "1234"
}

### 로그인
POST http://localhost:7777/users/log-in
Content-Type: application/json

{
    "username": "아무개",
    "password": "1234"
}