-- AlterTable
ALTER TABLE "Investment" ALTER COLUMN "amount" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Startup" ADD COLUMN     "acc" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "comparisonCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "mySelectionCount" INTEGER NOT NULL DEFAULT 0,
ALTER COLUMN "totalAmount" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "salesRevenue" SET DATA TYPE DOUBLE PRECISION;
