
import ModalPassword from "../../components/modal/modalPassword";
import PopupTwoButton from "../../components/modal/PopupOneButton";
import PopupTwoButton from "../../components/modal/PopupTwoButton";


      <div style={{ marginBottom: "20px" }}>
        <PopupOneButton size="big" onClose={() => {}} onDelete={() => {}} />
      </div>
      <PopupOneButton size="small" onClose={() => {}} onDelete={() => {}} />


      <div style={{ marginBottom: "20px" }}>
        <PopupTwoButton size="big" onClose={() => {}} onDelete={() => {}} />
      </div>
      <PopupTwoButton size="small" onClose={() => {}} onDelete={() => {}} />





// default index
    <Wrap>
        <Title>ex. hello!</Title>
        <StartButton onClick={goToCompanyDetail}>시작하기</StartButton>
      </Wrap>




// BtnDelete
<BtnDelete onClick={handleDelete} />                    // 기본: 삭제하기
<BtnDelete onClick={handleConfirm} type="confirm" />    // 확인
<BtnDelete onClick={handleDelete} size="small" />       // 작은 삭제 버튼
<BtnDelete onClick={handleConfirm} size="small" type="confirm" /> // 작은 확인 버튼


//ModalPassword
<ModalPassword size="big" onClose={() => {}} onDelete={() => {}} />
<ModalPassword size="small" onClose={() => {}} onDelete={() => {}} />
      

// PopupOneButton
<PopupOneButton size="big" type="error" onClose={() => {}} onDelete={() => {}} />
<PopupOneButton size="big" type="success" onClose={() => {}} onDelete={() => {}} />
<PopupOneButton size="small" type="error" onClose={() => {}} onDelete={() => {}} />
<PopupOneButton size="small" type="success" onClose={() => {}} onDelete={() => {}} />

