
import ModalPassword from "../../components/modal/modalPassword";

      <ModalPassword size="big" onClose={() => {}} onDelete={() => {}} />
      <ModalPassword size="small" onClose={() => {}} onDelete={() => {}} />
      