복붙하실때 import 확인 필수
복붙하실때 import 확인 필수
복붙하실때 import 확인 필수

//기업 비교하기 버튼
props는 
<BtnLarge type={"black"} size={"big"} />
<BtnLarge type={"orange"} size={"big"} />
<BtnLarge type={""} size={"big"} />
<BtnLarge type={"black"} size={"small"} />
<BtnLarge type={"orange"} size={"small"} />
<BtnLarge type={""} size={"small"} />

//(로딩그림) 기업 비교하기 버튼
props는 type=black/orange  size=big/small src=white/gray
<BtnMedium type={"black"} size={"big"} src={"gray"} />
<BtnMedium type={"orange"} size={"big"} src={"white"} />
<BtnMedium type={"black"} size={"small"} src={"gray"} />
<BtnMedium type={"orange"} size={"small"} src={"white"} />

//선택하기, 선택해제, 선택 완료 버튼
props는 text=choice/complete/cancel type=black/orange/none size=big/small src=exixtBig/existSmall/""
<BtnOutline text={"choice"} type={"orange"} size={"big"} src={""} />
<BtnOutline text={"choice"} type={"orange"} size={"small"} src={""} />
<BtnOutline text={"cancel"} type={"black"} size={"big"} src={""} />
<BtnOutline text={"cancel"} type={"black"} size={"small"} src={""} />
<BtnOutline
text={"complete"}
type={"white"}
size={"big"}
src={"existBig"}
/>
<BtnOutline
text={"complete"}
type={"white"}
size={"small"}
src={"existSmall"}
/>

//왼쪽 페이지 이동 버튼
<BtnLeft size={"big"} />
<BtnLeft size={"small"} />

//오른쪽 페이지 이동 버튼
<BtnRight size={"big"} />
<BtnRight size={"small"} />

//(숫자) 페이지 이동 버튼
<BtnPage text={1} size={"big"} />
<BtnPage text={2} size={"big"} />
<BtnPage text={3} size={"big"} />
<BtnPage text={4} size={"big"} />
<BtnPage text={5} size={"big"} />

<BtnPage text={1} size={"small"} />
<BtnPage text={2} size={"small"} />
<BtnPage text={3} size={"small"} />
<BtnPage text={4} size={"small"} />
<BtnPage text={5} size={"small"} />

//페이지네이션
<BtnPagination size={"big"} />
<BtnPagination size={"small"} />

//gnb 
<Gnb length={"long"} clickedcolor={"white"} color={"gray"}/>
<Gnb length={"long"} clickedcolor={"gray"} color={"white"}/>
<Gnb length={"middle"} clickedcolor={"white"} color={"gray"}/> 
<Gnb length={"middle"} clickedcolor={"gray"} color={"white"}/>
<Gnb length={"short"} clickedcolor={"white"} color={"gray"}/> 
<Gnb length={"short"} clickedcolor={"gray"} color={"white"}/>

//modal
<SelectMyEnterprise size={"big"} />
<SelectMyEnterprise size={"small"} />
<SelectComparison size={"big"} />
<SelectComparison size={"small"} />