import Search from "../../components/Search";


//search input창: 검색어를 입력해주세요, 입력하는 중입니다, 검색
// props는 size=big/medium/small type=none/searching

<Search size={"big"} state={"none"} />
<Search size={"medium"} state={"none"} />
<Search size={"small"} state={"none"} />
<Search size={"big"} state={"searching"} />
<Search size={"medium"} state={"searching"} />