import List from "../../components/List";
import Search from "../../components/Search";
import CardAdded from "../../components/CardAdded";


//search input창: 검색어를 입력해주세요, 입력하는 중입니다, 검색
// props는 size=big/medium/small status=none/searching

<Search size={"big"} state={"none"} />
<Search size={"medium"} state={"none"} />
<Search size={"small"} state={"none"} />
<Search size={"big"} state={"searching"} />
<Search size={"medium"} state={"searching"} />



// list
// props size=big/small, src, companyName, discription
<List
  size={"big"}
  src={}
  companyName={"코드잇"}
  discription={"에듀테크"}
/>
<List
  size={"small"}
  companyName={"코드잇2"}
  discription={"에듀테크2"}
/>


// cardAdded
// props size=big/small, src, companyName, discription
<CardAdded
  size={"big"}
  companyName={"코드잇1"}
  discription={"에듀테크1"}
/>
<CardAdded
  size={"small"}
  companyName={"코드잇2"}
  discription={"에듀테크2"}
/>